apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.servicename  }}-vs
  namespace: {{ .Release.Namespace }}
spec:
  gateways:
  - istio-system/preprod-gateway
  hosts:
  - {{ .Values.servicename  }}-test.applyproof.com
  http:
  - match:
    - uri:   
        prefix: /
    route:
    - destination:
        host: {{ .Values.servicename  }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: {{ .Values.targetport  }}
