apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels: 
    app: {{ .Values.servicename | quote }}
spec:
  type: NodePort]
  selector:
    app: {{ .Values.servicename | quote }}
  ports:
      - port: {{ .Values.port  }}
        targetPort: {{ .Values.targetport  }}
        nodePort: {{ .Values.nodeport  }}
  

---

apiVersion: v1
kind: Service
metadata:
  name: jenkins-jnlp
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.clusterport  }}
      targetPort: {{ .Values.clustertargetport }}
  selector:
    app: {{ .Values.servicename  }}